# Generated by Django 4.1 on 2024-11-16 16:47

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "image",
                    models.ImageField(unique=True, upload_to=main.models.image_upload),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("weddings", "Weddings"),
                            ("portraits", "Portraits"),
                            ("nature", "Nature"),
                        ],
                        default="portraits",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("additional_info", models.TextField(blank=True, null=True)),
                ("published_date", models.DateTimeField(auto_now_add=True)),
                (
                    "name",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details_name",
                        to="main.post",
                        to_field="name",
                    ),
                ),
                (
                    "post",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details_image",
                        to="main.post",
                        to_field="image",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to=main.models.gallery_upload)),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="main.post",
                    ),
                ),
            ],
        ),
    ]
