# Generated by Django 4.1 on 2024-11-16 16:56

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postdetails",
            name="post",
            field=models.ImageField(unique=True, upload_to=main.models.image_upload),
        ),
    ]
