# Generated by Django 4.1 on 2024-11-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_gallery_lift_side_content_gallery_right_side_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gallery",
            name="lift_side_content",
        ),
        migrations.RemoveField(
            model_name="gallery",
            name="right_side_content",
        ),
        migrations.AddField(
            model_name="post",
            name="lift_side_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="right_side_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
