# Generated by Django 5.1.3 on 2024-11-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_remove_gallery_lift_side_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("weddings", "Weddings"),
                    ("portraits", "Portraits"),
                    ("product", "Product"),
                    ("graduation", "Graduation"),
                    ("story", "Story"),
                    ("fashion", "Fashion"),
                ],
                default="portraits",
                max_length=50,
            ),
        ),
    ]
