# Generated by Django 4.1 on 2024-11-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_postdetails_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="lift_side_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gallery",
            name="right_side_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
